#!/usr/bin/env node
/**
 * Exports compiled ABIs to `abi/index.ts` so the web app and the indexer can
 * import them as typed constants.
 *
 * Run it through the workspace root so it happens for everyone the same way:
 *
 *   pnpm gen:abi
 *
 * Nobody hand writes an ABI. A hand written copy silently drifts out of date
 * the first time someone changes a function signature, and then the frontend
 * fails at runtime with an error that looks like a wallet problem.
 *
 * CI runs `pnpm gen` and fails if the committed output differs, so if you
 * change a contract you must commit the regenerated file with it.
 */

import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const artifactsDir = join(packageRoot, 'artifacts', 'src')
const outputDir = join(packageRoot, 'abi')
const outputFile = join(outputDir, 'index.ts')

/** Contracts worth exporting. Interfaces and test helpers are not. */
const EXPORTED = ['Election', 'ElectionFactory']

function findArtifact(name) {
  const stack = [artifactsDir]

  while (stack.length > 0) {
    const dir = stack.pop()

    let entries
    try {
      entries = readdirSync(dir)
    } catch {
      continue
    }

    for (const entry of entries) {
      const path = join(dir, entry)

      if (statSync(path).isDirectory()) {
        stack.push(path)
        continue
      }

      if (entry !== `${name}.json`) continue

      const artifact = JSON.parse(readFileSync(path, 'utf8'))
      if (Array.isArray(artifact.abi)) return artifact.abi
    }
  }

  return null
}

const missing = []
const sections = []

for (const name of EXPORTED) {
  const abi = findArtifact(name)

  if (abi === null) {
    missing.push(name)
    continue
  }

  const constantName = `${name.charAt(0).toLowerCase()}${name.slice(1)}Abi`
  sections.push(`export const ${constantName} = ${JSON.stringify(abi, null, 2)} as const\n`)
}

if (missing.length > 0) {
  console.error(`No compiled artifact for: ${missing.join(', ')}`)
  console.error('Run `pnpm --filter @veratalley/contracts compile` first.')
  process.exit(1)
}

const header = `// Generated by scripts/export-abi.js. Do not edit by hand.
// Regenerate with \`pnpm gen:abi\` from the repository root.

`

mkdirSync(outputDir, { recursive: true })
writeFileSync(outputFile, header + sections.join('\n'), 'utf8')

console.log(`Wrote ${EXPORTED.length} ABIs to abi/index.ts`)
