/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check, including whether the chain is reachable. */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @example 0.1.0 */
            version: string;
            /** @example 80002 */
            chainId: number;
            /**
             * @description Latest block height, read live from the chain. A decimal string, not a number: block heights exceed 2^53 and JavaScript loses precision above that.
             * @example 42906388
             */
            blockNumber: string;
        };
        /**
         * @description The frontend switches on this value and never on `message`, because messages get reworded and that would break the UI silently.
         * @enum {string}
         */
        ErrorCode: "NOT_FOUND" | "UNAUTHORIZED" | "VALIDATION_FAILED" | "BALLOT_NOT_FOUND" | "CHAIN_UNAVAILABLE" | "RATE_LIMITED" | "INTERNAL";
        ErrorResponse: {
            error: {
                code: components["schemas"]["ErrorCode"];
                /** @description Human readable. Never switch on this. */
                message: string;
                /**
                 * @description Quote this in a bug report to find the request in the logs.
                 * @example 01J8QW40T7X2
                 */
                traceId: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is up and the RPC endpoint answered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Too many requests from this client. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The RPC endpoint could not be reached. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
